---
title-block-style: plain
# date: 09/15/2024
# date-modified: last-modified
---

# Office Hours
<!-- # Office Hours {.unnumbered} -->

### When {.unnumbered}

- **Instructor:** Wednesday 1:30-3:30 (in-person and via Zoom, see below for details). You can drop by any time during the session, but if you want to guarantee a specific time slot you can do so by signing up here: <https://embruna.youcanbook.me/>. If you can't make it during the regularly scheduled office hours, you can send a message via Canvas to set up an appointment.

- **Teaching Assistant:** Tuesday 4:00-5:30 pm (in-person & online) or by appointment.

### Where {.unnumbered}

- **In-person:** The Tropical Ecology & Conservation Lab. The lab is located at 711 Newell Drive next to Rawlings Hall (between the bus stop and the parking garage). For directions you can use this [link to the lab on Google Maps](https://maps.app.goo.gl/xo13vJmj8WXAivpZ9).

- **Online:** To join Office Hours virtually use the Zoom Conferences link on the main menu of the course Canvas page. We are online the entire session.


::: {.callout-tip}


## Can you give me **one good reason** why I should go to Office Hours?

I can give you **ten**.   

1. To introduce yourself.
1. Get clarification on assignments. 
1. Argue about a topic that came up in class. 
1. Grab a (free) tea, coffee, or espresso in our lab kitchen. 
1. Make sure you understood the key points from a class session. 
1. Ask for feedback on ideas for course projects.
1. Get advice on successfully navigating academic life at UF. 
1. Discuss how to gain experience for your post-graduation goals. 
1. Request help arranging a study group.
1. You don't need a good reason...just come on by.

:::

------------------------------------------------------------------------