---
title-block-style: plain
# date: 09/15/2024
execute:
  echo: false
  warning: false
  message: false
prefer-html: true
format: pdf
extensions:
  fontawesome
  fontawesome5
---

```{r}

library(tidyverse)
library(kableExtra)
library(fontawesome)

```

<!-- # University Policies {.unnumbered} -->
# University Policies


<span style="color: #1F691B;"> {{< fa headphones >}} </span> **Student Accomodations:** Students with disabilities or learning barriers that would like to request academic accommodations should connect with the Disability Resource Center by visiting https://disability.ufl.edu/students/get-started/. Please share your letter with me and discuss access needs as early as possible in the semester so that I can do whatever is necessary to ensure your participation and learning.

<span style="color: #1F691B;"> {{< fa thumbs-up >}} </span> **Course Evaluations:** Students are expected to provide professional and respectful feedback on the quality of instruction in this course by completing course evaluations. Guidance on how to provide constructive feedback is available at https://gatorevals.aa.ufl.edu/students/. Students will be notified when the evaluation period opens. Summaries of course evaluation results are available to students at https://gatorevals.aa.ufl.edu/public-results/. Students can complete evaluations in three ways: (1) The email they receive from GatorEvals, (2) Their Canvas course menu under GatorEvals, and (3) The central portal at https://my-ufl.bluera.com.

<span style="color: #1F691B;"> {{< fa scale-balanced >}} </span> **University Honesty Policy:** UF students are bound by The Honor Pledge which states, “We, the members of the University of Florida community, pledge to hold ourselves and our peers to the highest standards of honor and integrity by abiding by the Honor Code. On all work submitted for credit by students at the University of Florida, the following pledge is either required or implied: On my honor, I have neither given nor received unauthorized aid in doing this assignment. The Honor Code (https://www.dso.ufl.edu/sccr/process/student-conduct-honor-code) specifies a number of behaviors that are in violation of this code and the possible sanctions. Furthermore, you are obligated to report any condition that facilitates academic misconduct to appropriate personnel. If you have questions or concerns, consult with the instructor or TAs.

<span style="color: #1F691B;"> {{< fa computer >}} </span> **Software Use:** All faculty, staff & students are required & expected to obey laws and legal agreements governing software use. Failure to do so can lead to monetary damages and/or criminal penalties for the individual violator. Because such violations are also against UF policies & rules, disciplinary action will be taken as appropriate.

<span style="color: #1F691B;"> {{< fa check >}} </span> **Attendance:** Requirements for class attendance & make-up exams, assignments, and other work are consistent with UF policies found at: https://catalog.ufl.edu/ugrad/current/regulations/info/attendance.aspx.

<span style="color: #1F691B;"> {{< fa microphone >}} </span> **In-Class Recording:** Students are allowed to record video or audio of class lectures. However, the purposes for which these recordings may be used are strictly controlled. The only allowable purposes are: (1)for personal educational use, (2)in connection with a complaint to the university, or (3)as evidence in, or in preparation for, a criminal or civil proceeding. All other purposes are prohibited.Specifically, students may not publish recorded lectures without the written consent of the instructor. A 'class lecture' is:an educational presentation intended to inform or teach enrolled students about a particular subject, including any instructor-led discussions that form part of the presentation, and delivered by any instructor hired or appointed by the University, or by a guest instructor, as part of a UF course. A class lecture does not include:lab sessions, student presentations, clinical presentations such as patient history, academic exercises involving solely student participation, assessments (quizzes, tests, exams), field trips, private conversations between students in the class or between a student and the faculty or lecturer during a class session. Publication without permission of the instructor is prohibited. To 'publish' means: to share, transmit, circulate, distribute, or provide access to a recording, regardless of format or medium, to another person (or persons), including but not limited to another student within the same class section. Additionally, a recording, or transcript of a recording, is considered published if it is posted on or uploaded to, in whole or in part, any media platform, including but not limited to social media, book, magazine, newspaper, leaflet, or third-party note/tutoring services. A student who publishes a recording without written consent may be subject to a civil cause of action instituted by a person injured by the publication and/or discipline under UF Regulation 4.040 Student Honor Code and Student Conduct Code.

<!-- ```{r} -->

<!-- #| echo: false -->
<!-- #| warning: false  -->
<!-- #| message: false -->
<!-- #| include: false -->
<!-- p1<- c("Student Accomodations") -->
<!-- t1<-c("Students with disabilities or learning barriers that would like to request academic accommodations should connect with the Disability Resource Center by visiting https://disability.ufl.edu/students/get-started/. Please share your letter with me and discuss access needs as early as possible in the semester so that I can do whatever is necessary to ensure your participation and learning.") -->

<!-- p2<- c("Course Evaluations") -->
<!-- t2<-c("Students are expected to provide professional and respectful feedback on the quality of instruction in this course by completing course evaluations. Guidance on how to provide constructive feedback is available at https://gatorevals.aa.ufl.edu/students/. Students will be notified when the evaluation period opens. Summaries of course evaluation results are available to students at https://gatorevals.aa.ufl.edu/public-results/. Students can complete evaluations in three ways: (1) The email they receive from GatorEvals, (2) Their Canvas course menu under GatorEvals, and (3) The central portal at https://my-ufl.bluera.com.") -->

<!-- p3<- c("University Honesty Policy") -->
<!-- t3<-c("UF students are bound by The Honor Pledge which states, “We, the members of the University of Florida community, pledge to hold ourselves and our peers to the highest standards of honor and integrity by abiding by the Honor Code. On all work submitted for credit by students at the University of Florida, the following pledge is either required or implied: On my honor, I have neither given nor received unauthorized aid in doing this assignment. The Honor Code (https://www.dso.ufl.edu/sccr/process/student-conduct-honor-code) specifies a number of behaviors that are in violation of this code and the possible sanctions. Furthermore, you are obligated to report any condition that facilitates academic misconduct to appropriate personnel. If you have questions or concerns, consult with the instructor or TAs.") -->

<!-- p5<- c("In-Class Recording") -->
<!-- t5<-c("Students are allowed to record video or audio of class lectures. However, the purposes for which these recordings may be used are strictly controlled. The only allowable purposes are: (1)for personal educational use, (2)in connection with a complaint to the university, or (3)as evidence in, or in preparation for, a criminal or civil proceeding. All other purposes are prohibited.Specifically, students may not publish recorded lectures without the written consent of the instructor. A 'class lecture' is:an educational presentation intended to inform or teach enrolled students about a particular subject, including any instructor-led discussions that form part of the presentation, and delivered by any instructor hired or appointed by the University, or by a guest instructor, as part of a UF course. A class lecture does not include:lab sessions, student presentations, clinical presentations such as patient history, academic exercises involving solely student participation, assessments (quizzes, tests, exams), field trips, private conversations between students in the class or between a student and the faculty or lecturer during a class session. Publication without permission of the instructor is prohibited. To 'publish' means: to share, transmit, circulate, distribute, or provide access to a recording, regardless of format or medium, to another person (or persons), including but not limited to another student within the same class section. Additionally, a recording, or transcript of a recording, is considered published if it is posted on or uploaded to, in whole or in part, any media platform, including but not limited to social media, book, magazine, newspaper, leaflet, or third-party note/tutoring services. A student who publishes a recording without written consent may be subject to a civil cause of action instituted by a person injured by the publication and/or discipline under UF Regulation 4.040 Student Honor Code and Student Conduct Code.") -->

<!-- p6<-c("Software Use") -->
<!-- t6<-c("All faculty, staff  & students are required  & expected to obey laws and legal agreements governing software use. Failure to do so can lead to monetary damages and/or criminal penalties for the individual violator. Because such violations are also against UF policies  & rules, disciplinary action will be taken as appropriate.") -->


<!-- p7<-c("Attendance") -->
<!-- t7<-c("Requirements for class attendance  & make-up exams, assignments, and other work are consistent with UF policies found at:  https://catalog.ufl.edu/ugrad/current/regulations/info/attendance.aspx.") -->
<!-- policy <- c(p1,p2,p3,p6,p7,p5) -->
<!-- text <- c(t1,t2,t3,t6,t7,t5) -->


<!-- icons = c( -->
<!--         fa("fas fa-headphones"), -->
<!--         fa("fas fa-thumbs-up"), -->
<!--         fa("fas fa-scale-balanced"), -->
<!--         fa("fas fa-computer"), -->
<!--         fa("fas fa-check"), -->
<!--         fa("fas fa-microphone") -->
<!--       ) -->

<!-- class_policies <- data.frame( -->
<!--   icons, -->
<!--   # blank_col = rep("  ",length(policy)), -->
<!--   policy = policy, -->
<!--   text = text, -->
<!--   stringsAsFactors = FALSE -->
<!--   ) -->

<!-- # %>% -->
<!-- #   mutate( -->
<!-- #     icon = file.path("./icons",icon)) -->

<!-- ``` -->

<!-- ```{r} -->

<!-- class_policies %>%  -->
<!--   # select(-icons) %>%  -->
<!--  kbl(# digits = 2, -->
<!--       align="cll", -->
<!--       # format="latex", -->
<!--       format="html", -->
<!--       row.names = FALSE, -->
<!--       table.attr = "quarto-disable-processing=true", -->
<!--       escape= FALSE, # must be false for FA icons -->
<!--       booktabs=T, -->
<!--       #     bottomrule = F, -->
<!-- #     # toprule = F, -->
<!-- #     # midrule = F, -->
<!-- #     escape = F, -->
<!-- col.names = NULL) %>%  -->
<!-- # , -->
<!-- #       linesep = "") %>%  -->
<!-- #   kable_styling( -->
<!-- # #     bootstrap_options = c("hover"), -->
<!-- #      # full_width = T, -->
<!-- #      latex_options= c("scale_down","HOLD_position"), -->
<!-- #      font_size = 12, -->
<!-- # position = "left") %>% -->
<!--  column_spec(1, width = "3em", color = "white",bold=T, background="#1F691B") %>%  -->
<!-- column_spec(2, width = "5em", color = "#1F691B",bold=T, background="white") %>% -->
<!-- column_spec(3, width = "45em", color = "black", background="white") %>%  -->
<!--   row_spec(1:6, extra_css = "border-bottom: 1px solid") %>%  -->
<!--   sub("\\\\toprule", "", .) %>% # Removes top line -->
<!--   sub("\\\\bottomrule", "", .) # remove bottom line -->

<!-- ``` -->


<!-- {{< fa thumbs-up >}}  -->