---
title-block-style: plain
# date: 09/15/2024
# date-modified: last-modified
execute:
  echo: false
  warning: false
  message: false
---

```{r setup_policies, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(fontawesome)
library(flextable)
library(kableExtra)
```

<!-- # UF Resources for Students {.unnumbered} -->
# UF Resources for Students

### Health, Safety, & Wellness {.unnumbered}

1. **Wellness and Mental Health** Students experiencing crises or personal problems that interfere with their general well-being are encouraged to utilize the university’s counseling resources. The Counseling & Wellness Center provides confidential counseling services at no cost for currently enrolled students. Resources are available on campus for students having personal problems or lacking clear career or academic goals, which interfere with their academic performance. *Visit <https://one.uf.edu/whole-gator/discover> for resources that are designed to help you thrive physically, mentally, and emotionally at UF.*

    -   *University Counseling & Wellness Center*, 3190 Radio Road, 352-392-1575. They can provide Counseling Services, Groups and Workshops, Outreach and Consultation, a Self-Help Library, and Wellness Coaching. <http://www.counseling.ufl.edu/>.

    -   *U Matter, We Care.* If you or someone you know is in distress, please contact [umatter\@ufl.edu](mailto:umatter@ufl.edu){.email}, 352-392-1575, or visit U Matter, We Care website (www.umatter.ufl.edu/) to refer or report a concern and a team member will reach out to the student in distress.

1. **Student Health Care Center** Call 352-392-1161 for 24/7 information to help you find the care you need, or visit the Student Health Care Center website.

1. **University Police Department** Visit UF Police Department website or call 352-392-1111 (or 9-1-1 for emergencies).

1. **UF Health Shands Emergency Room / Trauma Center** For immediate medical care call 352- 733-0111 or go to the emergency room at 1515 SW Archer Road, Gainesville, FL 32608; Visit the UF Health Emergency Room and Trauma Center website.

1. **Field and Fork Pantry** The Hitchcock Pantry can provide food and toiletries for students experi- encing food insecurity. <https://pantry.fieldandfork.ufl.edu/>.

### Academic Services {.unnumbered}



1. **E-learning technical support** Contact the UF Computing Help Desk: (352) 392-4357 or [helpdesk\@ufl.edu](mailto:helpdesk@ufl.edu){.email}.

1. **The Writing Studio** Help brainstorming, formatting, and writing papers. Daytime (9:30am-3:30pm): 2215 Turlington Hall, 352-846-1138. Evening (5:00pm-7:00pm): 1545 W University Avenue (Library West, Rm. 339).

1. **Career Connections Center** Reitz Union Ste 1300, (352) 392-1601. Career assistance & counseling services.

1. **Library Support** Various ways to receive assistance with respect to using the libraries or finding resources. Call 866-281-6309 or email [ask\@ufl.libanswers.com](mailto:ask@ufl.libanswers.com){.email} for more information.

1. **Academic Resources** 1317 Turlington Hall, Call (352) 392-2010 or to make a private appointment: 352- 392-6420. Email contact: [teaching-center\@ufl.edu](mailto:teaching-center@ufl.edu){.email}. General study skills and tutoring.

1. **Student Success Initiative** <http://studentsuccess.ufl.edu>.

1. **Student Complaints** [Office of the Ombuds](https://ombuds.ufl.edu/); Visit the [Complaint Portal webpage](https://ombuds.ufl.edu/complaint-portal/) for more information.

1. **Enrollment Management Complaints (Registrar, Financial Aid, Admissions)** View the Student Complaint Procedure webpage for more information.

1. **UF Student Success Initiative** Visit <https://studentsuccess.ufl.edu/> for resources that support your success as a UF student.
