project:
  type: book
  output-dir: book

css: format/style.css
  
book:
  title: "Syllabus"
  output-file: "wis2323-syllabus"
  # author: "Emilio M. Bruna"
  # date: 07/31/2025
  # date: last-modified
  # original-date: 11/15/2024
  # doi
  # url: https://herbvar-network.github.io/herbvar_manual
  # pdf-url: https://herbvar-network.github.io/herbvar_manual/herbvar-manual.pdf 
  date-format: long
  # license: "This work is licensed under CC BY-NC-SA 4.0. //To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/"
  # edition: "v4.0.0"
  # cover-image: images/cover.png
  search: true
  repo-url: https://github.com/BrunaLab/wis2323_syllabus
  # repo-actions: [edit]
  downloads: [pdf, epub]
  # sharing: [twitter, facebook]
  reader-mode: false
  favicon: images/cover.png
  page-footer:
    left: |
      WIS 2323 The Future of Rain Forests Course Syllabus
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    - 02-materials.qmd
    - 03-office_hours.qmd
    - 04-grades.qmd
    - 05-calendar.qmd
    - 06-faq.qmd
    - 07-policies.qmd
    - 08-resources.qmd
    - 09-readings.qmd
    - 10-slos.qmd
    
    # 
    # - part: "Course Introduction"
    #   chapters: 
    #     # - introduction/intro.qmd
    #     # - introduction/getting_involved.qmd
    #     # - introduction/Network_Structure.qmd
    #     # - introduction/data_overview.qmd
    #     # - introduction/herbvar_products.qmd
  

    
# bibliography: HerbVar.bib
csl: format/ecology.csl
format:

  html:
    title-block: false
    theme: 
      - cosmo
    filters: [format/remove_title.lua]
  # docx:
  #   toc: true
  #   number-sections: true
  #   highlight-style: github
  pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    # cover-image: images/cover.png
    filters: [format/remove_title.lua]
    # header-includes: |
    #   # \titlehead{\includegraphics[height=7in]{images/cover.png}}
    toc: false
    toc-depth: 1
    toc-title: Sections
    lof: false
    lot: false
    titlepage: false
    # Numbering
    number-sections: false
    # Fonts
    # fontfamily: libertinus
    # mainfont: Georgia
    # sansfont: Verdana
    # monofont: Source Code Pro
    fontsize: 10pt
    microtypeoptions: ["final"]
    # Colors
    colorlinks: true
    # Layout
    geometry:
      # - margin=0.75in
      - bindingoffset=0.0in
      - left=24mm
      - top=24mm
      - bottom=24mm
      - right=24mm
      # - heightrounded
      # - footskip=0.475in
      # - showframe
    # pagestyle: plain
    # Rendering
    keep-tex: true
    # https://quarto.org/docs/journals/templates.html#template-partials
    # https://github.com/quarto-dev/quarto-cli/discussions/1941
    # https://tex.stackexchange.com/questions/209993/how-to-customize-my-titlepage/210280#210280
    # https://github.com/nmfs-opensci/quarto_titlepages_v1
    # https://nmfs-opensci.github.io/quarto_titlepages_v1/03-how-to-use.html
    # https://tex.stackexchange.com/questions/209993/how-to-customize-my-titlepage/210280#210280
    # https://nrennie.rbind.io/blog/pdf-quarto/making-pretty-pdf-quarto/
    # https://github.com/nrennie/PrettyPDF
    include-in-header:
      text: |
        \usepackage{xcolor}
        \usepackage{sectsty}
        \usepackage{titlesec}
        \definecolor{customnavy}{RGB}{0, 0, 128}
        \sectionfont{\color{customnavy}}
        \subsectionfont{\color{customnavy}}   
        \subsubsectionfont{\color{customnavy}}   
        \usepackage{amssymb}
        \usepackage{pifont}
        \usepackage{wasysym}
        \usepackage{fontawesome5}
        \usepackage{etoolbox}
        \makeatletter
        \patchcmd{\scr@startchapter}{\if@openright\cleardoublepage\else\clearpage\fi}{}{}{}
        % Adjust spacing before and after headings
        \usepackage{titlesec}
        \titleformat{\section}
          {\normalfont\Large\bfseries\color{customnavy}\centering} % Format
          {} % Label (empty = no number)
          {0pt} % Separation between label and title
          {} % Before-code

        \titlespacing*{\section}{0pt}{0pt}{0pt}      % {left}{before}{after}
        \titlespacing*{\subsection}{0pt}{2pt}{2pt}   % {left}{before}{after}
        \titlespacing*{\subsubsection}{0pt}{2pt}{2pt}   % {left}{before}{after}
    # the previous three lines let a new chapter start on the same page as the ending chapter
    
      # - macros.tex
    # include-in-header: 
    #  - "format/PrettyPDF.tex"
    # include-before-body:
    #  - "format/pagestyle.tex
    #   - "format/_titlepage.tex" 
          
      
  epub:
      epub-cover-image: images/cover.png

# pdf-engine: xelatex
# see fpr engine-opt: https://stackoverflow.com/questions/74261557/quarto-rendering-pdf-running-xelatex-faster-in-rstudio    
editor: source

execute:
  # freeze: auto
  freeze: false