project:
  type: book
  output-dir: docs

css: format/style.css
  
book:
  title: "Syllabus - WIS 2323"
  output-file: "wis2323-syllabus"
  # author: "Emilio M. Bruna"
  # date: 07/31/2025
  # date: last-modified
  # original-date: 11/15/2024
  # doi
  # url: https://herbvar-network.github.io/herbvar_manual
  # pdf-url: https://herbvar-network.github.io/herbvar_manual/herbvar-manual.pdf 
  date-format: long
  # license: "This work is licensed under CC BY-NC-SA 4.0. //To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/"
  # edition: "v4.0.0"
  cover-image: images/cover.png
  search: true
  repo-url: https://github.com/BrunaLab/wis2323_syllabus
  # repo-actions: [edit]
  downloads: [pdf, epub]
  # sharing: [twitter, facebook]
  reader-mode: false
  favicon: images/cover.png
  page-footer:
    left: |
      WIS 2323 The Future of Rain Forests Course Syllabus
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    # - 02-gened.qmd
    - 03-materials.qmd
    - 04-office_hours.qmd
    - 05-grades.qmd
    - 06-calendar.qmd
    - 07-faq.qmd
    - 08-policies.qmd
    - 09-resources.qmd
    - 10-readings.qmd
    - 11-slos.qmd
    # - test.qmd
    # 
    # - part: "Course Introduction"
    #   chapters: 
    #     # - introduction/intro.qmd
    #     # - introduction/getting_involved.qmd
    #     # - introduction/Network_Structure.qmd
    #     # - introduction/data_overview.qmd
    #     # - introduction/herbvar_products.qmd
  

    
# bibliography: HerbVar.bib
csl: format/ecology.csl
format:

  html:
    theme: 
      - cosmo
    # filters: [format/remove_title.lua]
      
  pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    cover-image: images/cover.png
    # filters: [format/remove_title.lua]
    header-includes: |
      \titlehead{\includegraphics[height=7in]{images/cover.png}}
    toc: true
    toc-depth: 1
    toc-title: Table of Contents
    lof: false
    lot: false
    titlepage: false
    # Numbering
    number-sections: true
    # Fonts
    # fontfamily: libertinus
    mainfont: Georgia
    sansfont: Verdana
    # monofont: Source Code Pro
    fontsize: 10pt
    microtypeoptions: ["final"]
    # Colors
    colorlinks: true
    # Layout
    geometry:
      # - margin=0.75in
      - bindingoffset=0.0in
      - left=20mm
      - top=20mm
      - bottom=24mm
      - right=20mm
      # - heightrounded
      # - footskip=0.475in
      # - showframe
    # pagestyle: plain
    # Rendering
    keep-tex: true
    # https://quarto.org/docs/journals/templates.html#template-partials
    # https://github.com/quarto-dev/quarto-cli/discussions/1941
    # https://tex.stackexchange.com/questions/209993/how-to-customize-my-titlepage/210280#210280
    # https://github.com/nmfs-opensci/quarto_titlepages_v1
    # https://nmfs-opensci.github.io/quarto_titlepages_v1/03-how-to-use.html
    # https://tex.stackexchange.com/questions/209993/how-to-customize-my-titlepage/210280#210280
    # https://nrennie.rbind.io/blog/pdf-quarto/making-pretty-pdf-quarto/
    # https://github.com/nrennie/PrettyPDF
    include-in-header:
      text: |
        \usepackage{amssymb}
        \usepackage{pifont}
        \usepackage{wasysym}
        \usepackage{fontawesome5}
        \usepackage{etoolbox}
        \makeatletter
        \patchcmd{\scr@startchapter}{\if@openright\cleardoublepage\else\clearpage\fi}{}{}{}
        
    # the previous three lines let a new chapter start on the same page as the ending chapter
    
      # - macros.tex
    # include-in-header: 
    #  - "format/PrettyPDF.tex"
    # include-before-body:
    #  - "format/pagestyle.tex
    #   - "format/_titlepage.tex" 
          
      
  epub:
      epub-cover-image: images/cover.png

# pdf-engine: xelatex
# see fpr engine-opt: https://stackoverflow.com/questions/74261557/quarto-rendering-pdf-running-xelatex-faster-in-rstudio    
editor: source

execute:
  freeze: auto