# project:
#   type: website
#   output-dir: book/slides
# render:
#   - class_sessions/02_trf_narratives/slides/02_narratives.qmd
# format:
#   revealjs:
#     lib-dir: site_libs
#     slide-number: true
#     hash: true
#     incremental: true
#     mathjax: true
    
project:
  type: website
  output-dir: book/slides
format:
  revealjs:
    lib-dir: site_libs
    slide-number: true
    hash: true
    incremental: true
    mathjax: true