# Course Overview

### Course Description {.unnumbered}

This course investigates the fundamental issues addressed by scientists studying tropical rain forests, including what gave rise to their remarkable biodiversity, the drivers and consequences of deforestation, why people are fascinated by rain forests, cultural stereotypes about the tropics, and if forest conservation is compatible with socioeconomic development. ***By the end of the course students will be able to:***

-   Recognize and describe stereotypes about rain forests & their residents
-   Analyze rain forest tropes in art, literature, & popular culture
-   Discuss & evaluate hypotheses for the origins and maintenance of tropical biodiversity
-   Explain & compare human history in rain forests
-   Review contemporary threats to rain forests
-   Analyze and visualize data on deforestation
-   Review and contrast strategies for rain forest conservation & restoration
-   Identify rain forests in their daily lives & set personal goals for advancing their conservation
-   Produce materials for communicating about rain forests to family and peers

### When & Where {.unnumbered}

**When:** Tuesdays 3:00-3:50 and Thursdays 3:00-4:55\
**Where:** LIT 0231 (both days)

### Instructor & TA {.unnumbered}

**Instructor:** Dr. Emilio M. Bruna [embruna\@ufl.edu,  (352) 846-0634]   
**Teaching Assistant:** Priyanka Hari Haran [phariharan1\@ufl.edu, (352) 846-0527]

### Credits & Prerequisites {.unnumbered}

<!-- # GenEd, Quest, & Credit Information {.unnumbered} -->

**Credits:** 3\
**Prerequisites:** None\
**Quest Program:** Quest 2 <!-- -   GenEd Biological Sciences -->\
**GenEd Designation:** International

A minimum grade of C is required for Quest and General Education credit. Courses intended to satisfy Quest and General Education requirements cannot be taken S-U. <!-- *This course fulfills the following Quest and GenEd requirements:* -->

### Minors & Certificates {.unnumbered}

This course counts towards:  

- The Minor & Certificate in Latin American Studies. See  <https://www.latam.ufl.edu/academics/undergraduate-programs> for more information.

------------------------------------------------------------------------

<!-- This guide is a [Quarto Book](https://quarto.org/docs/books) hosted on the BrunaLab Github Site. Anyone can make suggestions for improving the contect either by [pull request](https://github.com/HerbVar-Network/project_manual/pulls) or by [posting an issue](https://github.com/HerbVar-Network/project_manual/issues) on the syllabus repository.  -->
