---
title: "Assignment 1 - Tropical Tropes Checklist"
author: "Emilio M. Bruna"
date: "`r format(Sys.time(), '%Y')`"
web: www.BrunaLab.org
github: embruna
twitter: https://twitter.com/BrunaLab
phone: (352) 514-3935
email: embruna@ufl.edu
geometry: margin=.7in
fontsize: 12pt
linkcolor: darkmidnightblue
urlcolor: darkmidnightblue
site: bookdown::bookdown_site
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot{}
- \fancyhead[R]{Movie Review Project - Tropical Tropes Checklist, p. \thepage}
- \fancyhead[L]{WIS 2323 - Rain Forests (`r format(Sys.time(), '%Y')`)}
- \usepackage[default]{sourcesanspro}
- \usepackage{parskip}
- \usepackage{xcolor}
- \AtBeginDocument{\let\maketitle\relax}
# - \usepackage{sectsty} \allsectionsfont{\raggedright}
- \usepackage{sectsty} \sectionfont{\centering}
- \usepackage{titlesec}
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
- \titlespacing{\section}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsubsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}


# output: pdf_document
classoption: landscape
output: pdf_document
  # word_document: default
# output: html_document
# weight: 5
    # df_print: paged
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile,
  encoding = encoding,
  output_dir = "./static/uploads")
  })
---


```{r setup_syllabus, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
library(here)
```
# DATASHEET - TROPICAL MOVIE TROPES
\vspace{0.4cm}

**REVIEWER NAME:** __________________________________   **MOVIE:** __________________________________ 
\vspace{0.2cm}
<!-- Below is a compendium of tropes commonly seen in movies about or set in rain forests, most of which came from the 'TV Tropes Website' ([https://tvtropes.org](https://tvtropes.org/)). The tropes are organized by category; each has a description, ID number, and shorthand code. Follow the links to read more background about a trope, see a list of movies in which it can be seen, and find related tropes. -->
<!-- \vspace{0.2cm}  -->

<!-- _**trope** (noun): In storytelling, a common, overused, or hackneyed theme, device, or situation; a cliché (pronunciation: /trōp/)._ -->


```{r tropes_table_edit, echo=FALSE,message = FALSE,warning=FALSE, results=FALSE}
# tropes<-readxl::read_excel("./class_materials/projects/movies/tropes.xlsx") %>%
tropes<-readxl::read_excel("./tropes.xlsx") %>%
  arrange(Category,Trope) %>% 
  select(-Category) %>% 
  filter(is.na(Focal)==FALSE) %>% 
  mutate(ID = row_number(), .before=Trope)


code <- strsplit(tropes$Trope, " ")
code<-sapply(code, function(x){
      toupper(paste(substring(x, 1, 1), collapse = ""))
  })
code<-as.data.frame(code)
code <- code %>% 
  mutate(ID = row_number())
str(code)
str(tropes)
tropes <- left_join(code,tropes) %>% 
  select(ID, Trope, Code=code,Description,Link)


tropes <- tropes %>%
  mutate(across(everything(), ~as.character(.x))) %>% 
  mutate(across(everything(), ~replace_na(.x, ""))) %>% 
  mutate(ID = trimws(ID)) %>% 
  rename("ID No."=ID) %>% 
  relocate(Code, .after="ID No.") %>% 
  select(-Code) %>% 
  select(-`ID No.`) %>% 
  mutate(Timestamp="___H____m", .before=1) %>% 
  mutate(Category=" ", .before=1)
# %>% 
#   mutate(Notes=" ") 



```


```{r tropes_table, echo=FALSE,message = FALSE,warning=FALSE}
# tropes %>% group_by(Category) %>% summarise(n())


# kbl(movies,
#       # digits = 2,
#       longtable=TRUE,
#       align="l",
#       format="latex",
#       row.names = FALSE,
#       escape= T,
#       booktabs=T,
#       linesep = "",
#       ) %>%

# kable(tropes, "html",


# for pdf only: 
tropes<-tropes %>% select(-Link)
  
kable(tropes, "latex",
  booktabs = TRUE,
  align="rccl",
  # caption = "Test",
  longtable = TRUE
) %>%
#    kable_styling(
#     position = "left",
#     bootstrap_options = c("hover","striped"),
#     latex_options = c("scale_down")
# ) %>%
  
  kable_paper("striped",
    
    latex_options = c("hold_position", "repeat_header", "scale_down"),
    font_size = 9) %>% # USE for PDF
   # font_size = 10 ) %>%
  pack_rows("PLOT & ACTION", 1,7, label_row_css = "background-color: #483D8B; color: #fff;") %>%
  pack_rows("CHARACTERS", 8, 23, label_row_css = "background-color: #483D8B; color: #fff;") %>%
  pack_rows("COSTUMES", 24, 26, label_row_css = "background-color: #483D8B; color: #fff;") %>%
  pack_rows("FLORA & FAUNA", 27, 32, label_row_css = "background-color: #483D8B; color: #fff;") %>%
  pack_rows("LOCATIONS", 33, 37, label_row_css = "background-color: #483D8B; color: #fff;") %>%
  pack_rows("DIALOGUE & SOUND", 38, 41, label_row_css = "background-color: #483D8B; color: #fff;") %>%
  row_spec(1:nrow(tropes)-1, hline_after = TRUE) %>%
  row_spec(0,hline_after = F, bold=T) %>%
  column_spec(1, width = "6em") %>%
  column_spec(2, width = "5em") %>%
  column_spec(3, width = "12em") %>%
  column_spec(4, width = "45em") 
# %>% 
  # column_spec(5, width = "12em") 
# %>%
#   column_spec(4, width = "5em") 
  # # column_spec(4, width = "6em") %>%
  # #   column_spec(5, width = "6em") %>%
  # #   # column_spec(4:6, width = "4em") %>%
  # # #   column_spec(4, width = "3em")
  # # #   
  # # #   row_spec(c(1:5),hline_after = T) %>%
  # row_spec(0, bold = T, color = "#483D8B", hline_after = F) %>%
  # row_spec(42, hline_after = T) %>%
  # row_spec(4, hline_after = T)
#   add_indent(6)
```
