---
title: "juice_game"
author: "Emilio M. Bruna"
mainfont: SourceSansPro
date: "11/4/2021"
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot{}
- \fancyhead[R]{Tropical Fruit Commodities, p. \thepage}
- \fancyhead[L]{WIS 2323 - Rain Forests (`r format(Sys.time(), '%Y')`)}
- \usepackage[default]{sourcesanspro}
- \usepackage{parskip}
- \usepackage{xcolor}
- \AtBeginDocument{\let\maketitle\relax}
- \usepackage{sectsty} \sectionfont{\centering}
- \usepackage{titlesec}
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
- \titlespacing{\section}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsubsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

USE THE PRIMNTER THAT PRINTS PHOTOBOTH STRIPS

\scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{DURIAN}}
\scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{CAM}}

\newpage


+----------------------------------------------------------+----------------------------------------------------------+
|                                                          |                                                          |
+----------------------------------------------------------+----------------------------------------------------------+
| \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{A}} | \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{A}} |
|                                                          |                                                          |
| \bigskip                                                 | \bigskip                                                 |
| \bigskip                                                 | \bigskip                                                 |
|                                                          |                                                          |
| \scalebox{2}{\fontsize{32pt}{4pt}\selectfont \textbf{B}} | \scalebox{2}{\fontsize{32pt}{4pt}\selectfont \textbf{B}} |
|                                                          |                                                          |
| \bigskip                                                 | \bigskip                                                 |
| \bigskip                                                 | \bigskip                                                 |
|                                                          |                                                          |
| \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{C}} | \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{C}} |
|                                                          |                                                          |
| \bigskip                                                 | \bigskip                                                 |
| \bigskip                                                 | \bigskip                                                 |
|                                                          |                                                          |
| \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{D}} | \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{D}} |
|                                                          |                                                          |
| \bigskip                                                 | \bigskip                                                 |
| \bigskip                                                 | \bigskip                                                 |
|                                                          |                                                          |
| \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{E}} | \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{E}} |
|                                                          |                                                          |
| \bigskip                                                 | \bigskip                                                 |
| \bigskip                                                 | \bigskip                                                 |
|                                                          |                                                          |
| \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{F}} | \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{F}} |
|                                                          |                                                          |
| \bigskip                                                 | \bigskip                                                 |
| \bigskip                                                 | \bigskip                                                 |
|                                                          |                                                          |
| \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{G}} | \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{G}} |
|                                                          |                                                          |
| \bigskip                                                 | \bigskip                                                 |
| \bigskip                                                 | \bigskip                                                 |
|                                                          |                                                          |
| \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{H}} | \scalebox{2}{\fontsize{32pt}{0pt}\selectfont \textbf{H}} |
|                                                          |                                                          |
| \bigskip                                                 | \bigskip                                                 |
| \bigskip                                                 | \bigskip                                                 |
+----------------------------------------------------------+----------------------------------------------------------+

\newpage


+--------------------------------------------------------+--------------------+--------------------------------------------------------+--------------------+
| \bigskip                                               |  \bigskip          | \bigskip                                               |  \bigskip          |
| Name: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                    | Name: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                    |
+--------------------------------------------------------+--------------------+--------------------------------------------------------+--------------------+
| \bigskip                                               |  \bigskip          | \bigskip                                               |  \bigskip          |
|**Fruit List**                                          | **Selections**     | **Fruit List**                                         | **Selections**     |
|                                                        |                    |                                                        |                    |
| 1.  Akee                                               | A = #**\_\_\_\_\_**| 1.  Akee                                               | A = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 2.  Atemoya                                            | B = #**\_\_\_\_\_**| 2.  Atemoya                                            | B = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 3.  Carambola                                          | C = #**\_\_\_\_\_**| 3.  Carambola                                          | C = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 4.  Soursop                                            | D = #**\_\_\_\_\_**| 4.  Soursop                                            | D = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 5.  Guava                                              | E = #**\_\_\_\_\_**| 5.  Guava                                              | E = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 6.  Jaboticaba                                         | F = #**\_\_\_\_\_**| 6.  Jaboticaba                                         | F = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 7.  Longan                                             | G = #**\_\_\_\_\_**| 7.  Longan                                             | G = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 8.  Lulo                                               | H = #**\_\_\_\_\_**| 8.  Lulo                                               | H = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 9.  Mamey Sapote                                       |                    | 9.  Mamey Sapote                                       |                    |
|                                                        |                    |                                                        |                    |
| 10. Mango                                              |                    | 10. Mango                                              |                    |
|                                                        |                    |                                                        |                    |
| 11. Nance                                              |                    | 11. Nance                                              |                    |
|                                                        |                    |                                                        |                    |
| 12. Papaya                                             |                    | 12. Papaya                                             |                    |
|                                                        |                    |                                                        |                    |
| 13. Passion Fruit                                      |                    | 13. Passion Fruit                                      |                    |
|                                                        |                    |                                                        |                    |
| 14. Pitaya                                             |                    | 14. Pitaya                                             |                    |
|                                                        |                    |                                                        |                    |
| 15. Star Apple                                         |                    | 15. Star Apple                                         |                    |
|                                                        |                    |                                                        |                    |
| 16. Tamarind                                           |                    | 16. Tamarind                                           |                    |
|                                                        |                    |                                                        |                    |
| 17. Cashew                                             |                    | 17. Cashew                                             |                    |
|                                                        |                    |                                                        |                    |
| 18. Tamarillo                                          |                    | 18. Tamarillo                                          |                    |
+--------------------------------------------------------+--------------------+--------------------------------------------------------+--------------------+

\bigskip 
\bigskip 

+--------------------------------------------------------+--------------------+--------------------------------------------------------+--------------------+
| \bigskip                                               |  \bigskip          | \bigskip                                               |  \bigskip          |
| Name: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                    | Name: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                    |
+--------------------------------------------------------+--------------------+--------------------------------------------------------+--------------------+
| \bigskip                                               |  \bigskip          | \bigskip                                               |  \bigskip          |
|**Fruit List**                                          | **Selections**     | **Fruit List**                                         | **Selections**     |
|                                                        |                    |                                                        |                    |
| 1.  Akee                                               | A = #**\_\_\_\_\_**| 1.  Akee                                               | A = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 2.  Atemoya                                            | B = #**\_\_\_\_\_**| 2.  Atemoya                                            | B = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 3.  Carambola                                          | C = #**\_\_\_\_\_**| 3.  Carambola                                          | C = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 4.  Soursop                                            | D = #**\_\_\_\_\_**| 4.  Soursop                                            | D = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 5.  Guava                                              | E = #**\_\_\_\_\_**| 5.  Guava                                              | E = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 6.  Jaboticaba                                         | F = #**\_\_\_\_\_**| 6.  Jaboticaba                                         | F = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 7.  Longan                                             | G = #**\_\_\_\_\_**| 7.  Longan                                             | G = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 8.  Lulo                                               | H = #**\_\_\_\_\_**| 8.  Lulo                                               | H = #**\_\_\_\_\_**|
|                                                        |                    |                                                        |                    |
| 9.  Mamey Sapote                                       |                    | 9.  Mamey Sapote                                       |                    |
|                                                        |                    |                                                        |                    |
| 10. Mango                                              |                    | 10. Mango                                              |                    |
|                                                        |                    |                                                        |                    |
| 11. Nance                                              |                    | 11. Nance                                              |                    |
|                                                        |                    |                                                        |                    |
| 12. Papaya                                             |                    | 12. Papaya                                             |                    |
|                                                        |                    |                                                        |                    |
| 13. Passion Fruit                                      |                    | 13. Passion Fruit                                      |                    |
|                                                        |                    |                                                        |                    |
| 14. Pitaya                                             |                    | 14. Pitaya                                             |                    |
|                                                        |                    |                                                        |                    |
| 15. Star Apple                                         |                    | 15. Star Apple                                         |                    |
|                                                        |                    |                                                        |                    |
| 16. Tamarind                                           |                    | 16. Tamarind                                           |                    |
|                                                        |                    |                                                        |                    |
| 17. Cashew                                             |                    | 17. Cashew                                             |                    |
|                                                        |                    |                                                        |                    |
| 18. Tamarillo                                          |                    | 18. Tamarillo                                          |                    |
+--------------------------------------------------------+--------------------+--------------------------------------------------------+--------------------+
