---
title: 'WIS 2323 - "Group Work Evaluation'
author: "Emilio M. Bruna"
date: "`r format(Sys.time(), '%Y')`"
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: darkmidnightblue
urlcolor: darkmidnightblue
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot{}
- \fancyhead[R]{Group and Self Evaluation, p. \thepage}
- \fancyhead[L]{WIS 2323 - Rain Forests (`r format(Sys.time(), '%Y')`)}
- \usepackage[default]{sourcesanspro}
- \usepackage{parskip}
- \usepackage{xcolor}
- \AtBeginDocument{\let\maketitle\relax}
- \usepackage{sectsty} \sectionfont{\centering}
- \usepackage{titlesec}
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
- \titlespacing{\section}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsubsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile,
  output_file = "Group_Work_Eval.pdf",
  encoding = encoding,
  output_dir = "./static/uploads")
  })
---

```{r setup, include=FALSE}

```

<!-- From: https://www.cmu.edu/teaching/designteach/design/instructionalstrategies/groupprojects/tools/index.html -->

## Group Work Evaluation

&nbsp;

Please use this form to evaluate the contributions of each team member to the group effort. Consider attendance and participation in team meetings, individual contributions to idea generation and research, communication within the group, etc. ***These evaluations are completely confidential and will never be shown to your team members.*** Please respond as honestly as possible.

**Instructions:** Please allocate a total of 100 percentage points among your team members, including yourself, with higher percentages going to those members who contributed most. In the case of equal contribution, points should be divided equally among team members.

> Your name: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

&nbsp;

> Team name: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

&nbsp;
&nbsp;
&nbsp;
&nbsp;

| Group Member | Name | % Points |
|------|------|------|
| Yourself |________________________|______|
| Member 1 |________________________|______|
| Member 2 |________________________|______|
| Member 3 |________________________|______|
| Member 4 |________________________|______|
| Member 5 |________________________|______|
| Member 6 |________________________|______|
|          |  |  **Total: 100%** |
