---
title: "Office Hours"
title-block-style: none
# date: 09/15/2024
# date-modified: last-modified
fig-alt: "light bulb to indicate imporant information."
---


<!-- # Office Hours   -->

# Office Hours 



::: {.callout-tip}

## Can you give me **one good reason** why I should go to Office Hours?

I can give you **ten**.   

1. To introduce yourself.
1. Get clarification on assignments. 
1. Argue about a topic that came up in class. 
1. Grab a (free) tea, coffee, or espresso in our lab kitchen. 
1. Make sure you understood the key points from a class session. 
1. Ask for feedback on ideas for course projects.
1. Get advice on successfully navigating academic life at UF. 
1. Discuss how to gain experience for your post-graduation goals. 
1. Request help arranging a study group.
1. You don't need a good reason...just come on by.

:::

## Instructor - Prof. Bruna  {.unnumbered}  


- **When:** Friday 2:00-3:30 or by appointment. **You can come to Office Hours any time during the session, either in person OR via zoom, without setting up an appointment - simply come by or log on.**. If you want to reserve a specific time, however, you can do so here: <https://embruna.youcanbook.me/>. _If you can't make it during the regularly scheduled office hours, send a message via Canvas and we will set up an appointment for another day and time._

- **Where: In-person:** The Tropical Ecology & Conservation Lab is located at 711 Newell Drive next to Rawlings Hall (The white house between the bus stop and the parking garage). The location and directions are on [Google Maps](https://maps.app.goo.gl/xo13vJmj8WXAivpZ9). Dr. Bruna's office is in the back of the building: either knock on the front door and go through the conference room to his office OR walk around to the back of the building and knock on the private entrance (the door to the right of the palm tree; look for the window with all the plants).  

- **Where: Online:** To join Office Hours virtually use the 'Zoom Conferences' link on the main menu of the course Canvas page. We will be online the entire session.


## Teaching Assistant - Ashra Kunwar {.unnumbered}  

 **When:** Tuesday 2:00-4:00 pm or by appointment.  
 
- **Online:** To join Office Hours virtually use the 'Zoom Conferences' link on the main menu of the course Canvas page. We will be online the entire session.
